@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Register New Patient</h3>
    <a href="{{ route('patients.index') }}" class="btn btn-outline-secondary">Back</a>
</div>

@if($errors->any())
    <div class="alert alert-danger">
        <div><strong>There were some problems with your input:</strong></div>
        <ul class="mb-0">
            @foreach($errors->all() as $e)
                <li>{{ $e }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form method="POST" action="{{ route('patients.store') }}">
    @csrf

    <div class="row">
        <div class="col-md-3 mb-3">
            <label class="form-label">Patient Code</label>
            <input type="text" class="form-control" value="{{ old('patient_code', $patient->patient_code ?? '') }}" readonly>
            <div class="form-text">Auto-generated by the system and cannot be edited.</div>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">First Name <span class="text-danger">*</span></label>
            <input type="text" name="first_name" class="form-control" value="{{ old('first_name', $patient->first_name ?? '') }}" required>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Middle Name</label>
            <input type="text" name="middle_name" class="form-control" value="{{ old('middle_name', $patient->middle_name ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Last Name <span class="text-danger">*</span></label>
            <input type="text" name="last_name" class="form-control" value="{{ old('last_name', $patient->last_name ?? '') }}" required>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 mb-3">
            <label class="form-label">Gender <span class="text-danger">*</span></label>
            @php $g = old('gender', $patient->gender ?? ''); @endphp
            <select name="gender" class="form-select" required>
                <option value="">-- Select --</option>
                <option value="male" {{ $g === 'male' ? 'selected' : '' }}>Male</option>
                <option value="female" {{ $g === 'female' ? 'selected' : '' }}>Female</option>
                <option value="other" {{ $g === 'other' ? 'selected' : '' }}>Other</option>
            </select>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Date of Birth</label>
            <input type="date" name="dob" class="form-control" value="{{ old('dob', optional($patient->dob)->format('Y-m-d')) }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">National ID Number</label>
            <input type="text" name="national_id_number" class="form-control" value="{{ old('national_id_number', $patient->national_id_number ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Passport Number</label>
            <input type="text" name="passport_number" class="form-control" value="{{ old('passport_number', $patient->passport_number ?? '') }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3">
            <label class="form-label">Avatar (auto-selected)</label>
            <div class="d-flex align-items-center">
                @php
                    $avatarPath = $g === 'female'
                        ? 'images/avatars/female.svg'
                        : ($g === 'male' ? 'images/avatars/male.svg' : 'images/avatars/other.svg');
                @endphp
                <img src="{{ asset($avatarPath) }}" alt="Avatar" width="80" height="80" class="rounded object-fit-cover">
                <span class="ms-2 text-muted small">Avatar is selected based on gender and cannot be changed.</span>
            </div>
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Email</label>
            <input type="email" name="email" class="form-control" value="{{ old('email', $patient->email ?? '') }}">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Contact Number</label>
            <input type="text" name="contact_number" class="form-control" value="{{ old('contact_number', $patient->contact_number ?? '') }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 mb-3">
            <label class="form-label">Residential Address</label>
            <input type="text" name="residential_address" class="form-control" value="{{ old('residential_address', $patient->residential_address ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Race</label>
            @php $race = old('race', $patient->race ?? ''); @endphp
            <select name="race" class="form-select">
                <option value="">-- Select --</option>
                @foreach(['Black', 'White', 'Asian', 'Hispanic', 'Mixed', 'Other'] as $r)
                    <option value="{{ $r }}" {{ $race === $r ? 'selected' : '' }}>{{ $r }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Religion</label>
            @php $religion = old('religion', $patient->religion ?? ''); @endphp
            <select name="religion" class="form-select">
                <option value="">-- Select --</option>
                @foreach(['Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Judaism', 'Traditional', 'Other'] as $rel)
                    <option value="{{ $rel }}" {{ $religion === $rel ? 'selected' : '' }}>{{ $rel }}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 mb-3">
            <label class="form-label">Language</label>
            <input type="text" name="language" class="form-control" value="{{ old('language', $patient->language ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Denomination</label>
            @php $denom = old('denomination', $patient->denomination ?? ''); @endphp
            <select name="denomination" class="form-select">
                <option value="">-- Select --</option>
                @foreach(['Catholic', 'Protestant', 'Orthodox', 'Evangelical', 'Pentecostal', 'Other'] as $d)
                    <option value="{{ $d }}" {{ $denom === $d ? 'selected' : '' }}>{{ $d }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Marital Status</label>
            <input type="text" name="marital_status" class="form-control" value="{{ old('marital_status', $patient->marital_status ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Occupation</label>
            <input type="text" name="occupation" class="form-control" value="{{ old('occupation', $patient->occupation ?? '') }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 mb-3">
            <label class="form-label">Blood Group</label>
            @php $bg = old('blood_group', $patient->blood_group ?? ''); @endphp
            <select name="blood_group" class="form-select">
                <option value="">-- Select --</option>
                @foreach(['O+', 'A+', 'B+', 'AB+', 'O−', 'A−', 'B−', 'AB−'] as $group)
                    <option value="{{ $group }}" {{ $bg === $group ? 'selected' : '' }}>{{ $group }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Allergies</label>
            <input type="text" name="allergies" class="form-control" value="{{ old('allergies', $patient->allergies ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Disabilities</label>
            <input type="text" name="disabilities" class="form-control" value="{{ old('disabilities', $patient->disabilities ?? '') }}">
        </div>
        <div class="col-md-3 mb-3">
            <label class="form-label">Special Diet</label>
            <input type="text" name="special_diet" class="form-control" value="{{ old('special_diet', $patient->special_diet ?? '') }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3">
            <label class="form-label">Medical Aid Provider</label>
            <input type="text" name="medical_aid_provider" class="form-control" value="{{ old('medical_aid_provider', $patient->medical_aid_provider ?? '') }}">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Medical Aid Number</label>
            <input type="text" name="medical_aid_number" class="form-control" value="{{ old('medical_aid_number', $patient->medical_aid_number ?? '') }}">
        </div>
    </div>

    <div class="mb-3">
        <label class="form-label">Special Medical Requirements</label>
        <textarea name="special_medical_requirements" rows="2" class="form-control">{{ old('special_medical_requirements', $patient->special_medical_requirements ?? '') }}</textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">Current Medications</label>
        <textarea name="current_medications" rows="2" class="form-control">{{ old('current_medications', $patient->current_medications ?? '') }}</textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">Past Medical History</label>
        <textarea name="past_medical_history" rows="2" class="form-control">{{ old('past_medical_history', $patient->past_medical_history ?? '') }}</textarea>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3">
            <label class="form-label">Next of Kin Name</label>
            <input type="text" name="next_of_kin_name" class="form-control" value="{{ old('next_of_kin_name', $patient->next_of_kin_name ?? '') }}">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Relationship</label>
            <input type="text" name="next_of_kin_relationship" class="form-control" value="{{ old('next_of_kin_relationship', $patient->next_of_kin_relationship ?? '') }}">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Next of Kin Contact</label>
            <input type="text" name="next_of_kin_contact_number" class="form-control" value="{{ old('next_of_kin_contact_number', $patient->next_of_kin_contact_number ?? '') }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 mb-3">
            <label class="form-label">Next of Kin Email</label>
            <input type="email" name="next_of_kin_email" class="form-control" value="{{ old('next_of_kin_email', $patient->next_of_kin_email ?? '') }}">
        </div>
        <div class="col-md-6 mb-3">
            <label class="form-label">Next of Kin Address</label>
            <input type="text" name="next_of_kin_address" class="form-control" value="{{ old('next_of_kin_address', $patient->next_of_kin_address ?? '') }}">
        </div>
    </div>

    <div class="d-flex justify-content-end">
        <button class="btn btn-primary">Save</button>
    </div>
</form>
@endsection
